version: '3'
services:
  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
networks:
  bank:
    ipam:
      driver: default
      config:
        - subnet: '172.21.0.4/24'